# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(blank=True, max_length=200)),
                ('mail', models.EmailField(blank=True, max_length=70, primary_key=True, serialize=False)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Paris')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='bridge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
    ]
