# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('NETWORKID', models.CharField(max_length=200, null=True)),
                ('NODEID', models.CharField(default='0', max_length=200)),
                ('VERSION', models.CharField(default='V0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('API_KEY', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('NETWORKID', models.CharField(max_length=200, null=True)),
                ('NODEID', models.CharField(default='0', max_length=200)),
                ('VERSION', models.CharField(default='V0', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(blank=True, max_length=200)),
                ('API_KEY', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, primary_key=True, serialize=False)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Paris')),
                ('password', models.CharField(max_length=30)),
                ('prefered_channel', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=200)),
                ('lastVersion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='TYPE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Type'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='bridge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Bridge'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Sensor'),
        ),
        migrations.AddField(
            model_name='channel',
            name='sensors',
            field=models.ManyToManyField(related_name='channels', to='website.Sensor'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='bridge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
    ]
