# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160204_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPE', models.CharField(max_length=200)),
                ('lastVersion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bridge',
            name='NETWORKID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bridge',
            name='NODEID',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='bridge',
            name='VERSION',
            field=models.CharField(default='V0', max_length=200),
        ),
        migrations.AddField(
            model_name='sensor',
            name='NETWORKID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='NODEID',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='sensor',
            name='TYPE',
            field=models.CharField(default='Bridge', max_length=200),
        ),
        migrations.AddField(
            model_name='sensor',
            name='VERSION',
            field=models.CharField(default='V0', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='API_KEY',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Sensor'),
        ),
    ]
