# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160215_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
