# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='sensors',
            field=models.ManyToManyField(related_name='channels', to='website.Sensor'),
        ),
    ]
