# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160216_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefered_channel',
            field=models.CharField(default='nochannel', max_length=200),
            preserve_default=False,
        ),
    ]
